/* <digestive-system> — a dependency-free custom element wrapping the
   digestive-tract illustration. Generated by assets/digestive-system.gen.py.

   Usage:
     <link rel="stylesheet" href="digestive-system.css">
     <script type="module" src="digestive-system.js"></script>
     <digestive-system interactive labels caption lang="ar"></digestive-system>

   Attributes
     interactive   hover / focus / click highlighting
     labels        static name chips positioned over each organ
     caption       caption line naming the active organ
     lang="ar"     Arabic organ names (any other value = English)
     selected      organ id; reflected, settable from outside

   Events (bubbling, composed)
     organ-hover   detail: { id, name } | { id: null }
     organ-select  detail: { id, name }

   The element renders in the light DOM on purpose, so host pages can theme it
   with plain CSS. Each instance carries its own <defs> with id-scoped
   gradients, so several differently themed instances can coexist.
*/

export const VIEWBOX = { width: 1070, height: 1440 };

export const ORGANS = [
  { id: "oesophagus", en: "Oesophagus", ar: "المريء", x: 44.0, y: 12.0 },
  { id: "stomach", en: "Stomach", ar: "المعدة", x: 82.0, y: 24.0 },
  { id: "duodenum", en: "Duodenum", ar: "الاثنا عشر", x: 26.0, y: 39.0 },
  { id: "small-intestine", en: "Small intestine", ar: "الأمعاء الدقيقة", x: 58.0, y: 68.0 },
  { id: "large-intestine", en: "Large intestine", ar: "الأمعاء الغليظة (القولون)", x: 21.0, y: 55.0 },
  { id: "appendix", en: "Appendix", ar: "الزائدة الدودية", x: 27.0, y: 93.0 },
  { id: "rectum", en: "Rectum", ar: "المستقيم", x: 74.0, y: 90.0 }
];

export const DEFS = `    <linearGradient id="ds-g-tube" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="var(--ds-rim-1,#8ED9F8)"/>
      <stop offset="0.35" stop-color="color-mix(in oklab, var(--ds-rim-1) 62%, var(--ds-rim-2))"/>
      <stop offset="0.72" stop-color="color-mix(in oklab, var(--ds-rim-1) 26%, var(--ds-rim-2))"/>
      <stop offset="1" stop-color="var(--ds-rim-2,#5F6BDA)"/>
    </linearGradient>
    <linearGradient id="ds-g-colon" x1="0.1" y1="0" x2="0.9" y2="1">
      <stop offset="0" stop-color="var(--ds-colon-1,#84D6F8)"/>
      <stop offset="0.32" stop-color="color-mix(in oklab, var(--ds-colon-1) 66%, var(--ds-colon-2))"/>
      <stop offset="0.68" stop-color="color-mix(in oklab, var(--ds-colon-1) 28%, var(--ds-colon-2))"/>
      <stop offset="1" stop-color="var(--ds-colon-2,#5A66D7)"/>
    </linearGradient>
    <radialGradient id="ds-g-stomach" cx="0.34" cy="0.28" r="0.86">
      <stop offset="0" stop-color="var(--ds-core,#E4F8FE)"/>
      <stop offset="0.30" stop-color="color-mix(in oklab, var(--ds-core) 46%, var(--ds-rim-1))"/>
      <stop offset="0.66" stop-color="color-mix(in oklab, var(--ds-rim-1) 72%, var(--ds-rim-2))"/>
      <stop offset="1" stop-color="var(--ds-rim-2,#6C86E6)"/>
    </radialGradient>
    <filter id="ds-f-glow" x="-25%" y="-25%" width="150%" height="150%">
      <feGaussianBlur stdDeviation="11"/>
    </filter>
    <filter id="ds-f-soft" x="-25%" y="-25%" width="150%" height="150%">
      <feGaussianBlur stdDeviation="2.6"/>
    </filter>
    <filter id="ds-f-halo" x="-30%" y="-30%" width="160%" height="160%">
      <feGaussianBlur stdDeviation="18"/>
    </filter>`;

/** Gradient + filter definitions, and the artwork that references them.
 *  Exported for hand-rolled integrations: inline `<svg><defs>${DEFS}</defs>
 *  ${ART}</svg>` and the illustration renders without the custom element. */
export const ART = `  <g class="ds-halo" aria-hidden="true" filter="url(#ds-f-halo)">
    <path d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="70"/>
    <path d="M 651,700 C 578,724 500,690 452,738 C 400,790 424,856 494,856 C 558,856 602,818 656,838 C 722,862 762,908 746,962 C 730,1016 660,1024 616,988 C 566,948 588,884 532,868 C 472,851 420,902 442,958 C 462,1008 524,1018 548,1064 C 574,1112 532,1156 482,1146 C 428,1135 418,1076 470,1046 C 522,1016 596,1042 640,1082 C 676,1114 668,1178 616,1196 C 560,1214 502,1180 470,1140" stroke-width="56"/>
    <path d="M 656,336 C 690,306 744,286 800,290 C 872,296 924,348 928,424 C 932,498 898,562 838,592 C 790,616 736,614 692,592 C 650,572 606,550 568,538 C 542,530 516,520 500,508 C 494,494 498,482 510,474 C 556,488 606,506 644,522 C 676,534 704,526 718,500 C 730,472 726,428 706,390 C 692,364 674,346 656,336 Z" stroke-width="40"/>
    <path d="M 611,-10 C 611,90 604,190 606,250 C 608,302 626,330 664,346" stroke-width="30"/>
  </g>
  <g class="ds-glows ds-glow" aria-hidden="true" filter="url(#ds-f-glow)">
    <g class="ds-organ-glow" data-organ="large-intestine">
      <path d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="52"/>
    </g>
    <g class="ds-organ-glow" data-organ="appendix">
      <path d="M 322,1222 C 342,1262 352,1290 348,1310" stroke-width="28"/>
    </g>
    <g class="ds-organ-glow" data-organ="rectum">
      <path d="M 654,1262 C 620,1288 602,1318 600,1356 C 598,1396 599,1424 600,1452" stroke-width="58"/>
    </g>
    <g class="ds-organ-glow" data-organ="small-intestine">
      <path d="M 700,760 C 766,778 800,840 770,890 C 744,928 692,934 664,910" stroke-width="54"/>
      <path d="M 396,898 C 342,924 338,992 390,1014 C 432,1032 478,1010 486,974" stroke-width="54"/>
      <path d="M 556,1162 C 620,1198 702,1176 730,1124 C 750,1086 732,1044 702,1030" stroke-width="54"/>
      <path d="M 468,782 C 414,808 404,866 446,894" stroke-width="54"/>
      <path d="M 592,910 C 644,896 692,920 702,960" stroke-width="54"/>
      <path d="M 522,1094 C 470,1084 428,1110 426,1148" stroke-width="54"/>
      <path d="M 612,616 C 668,634 706,624 736,640 C 772,660 776,706 748,724" stroke-width="54"/>
      <path d="M 786,690 C 830,708 846,764 812,800 C 782,832 736,826 716,796" stroke-width="54"/>
      <path d="M 358,986 C 318,1014 320,1074 362,1096 C 396,1114 436,1100 450,1072" stroke-width="54"/>
      <path d="M 640,1128 C 594,1150 548,1136 522,1104" stroke-width="54"/>
      <path d="M 754,996 C 800,1020 812,1084 774,1116 C 742,1144 698,1136 680,1108" stroke-width="54"/>
      <path d="M 434,724 C 386,748 372,802 398,838" stroke-width="54"/>
      <path d="M 386,1128 C 424,1166 486,1176 524,1152" stroke-width="54"/>
      <path d="M 664,1044 C 620,1060 578,1046 560,1010" stroke-width="54"/>
      <path d="M 480,932 C 528,908 586,928 604,972" stroke-width="54"/>
      <path d="M 728,860 C 692,832 686,788 712,764" stroke-width="54"/>
      <path d="M 340,1046 C 306,1074 306,1122 340,1146" stroke-width="54"/>
      <path d="M 596,1204 C 654,1228 716,1212 742,1170" stroke-width="54"/>
      <path d="M 651,700 C 578,724 500,690 452,738 C 400,790 424,856 494,856 C 558,856 602,818 656,838 C 722,862 762,908 746,962 C 730,1016 660,1024 616,988 C 566,948 588,884 532,868 C 472,851 420,902 442,958 C 462,1008 524,1018 548,1064 C 574,1112 532,1156 482,1146 C 428,1135 418,1076 470,1046 C 522,1016 596,1042 640,1082 C 676,1114 668,1178 616,1196 C 560,1214 502,1180 470,1140" stroke-width="58"/>
    </g>
    <g class="ds-organ-glow" data-organ="duodenum">
      <path d="M 504,492 C 456,480 420,506 410,554 C 397,614 424,660 476,678 C 532,698 600,688 648,704" stroke-width="56"/>
    </g>
    <g class="ds-organ-glow" data-organ="oesophagus">
      <path d="M 611,-10 C 611,90 604,190 606,250 C 608,302 626,330 664,346" stroke-width="32"/>
    </g>
  </g>
  <g class="ds-art">
    <g class="ds-organ" data-organ="large-intestine" aria-label="Large intestine">
      <path class="ds-edge" d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="45.0"/>
      <path class="ds-edge" d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="75" stroke-dasharray="1 36" stroke-linecap="round"/>
      <path class="ds-lb" stroke="url(#ds-g-colon)" d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="70" stroke-dasharray="1 36" stroke-linecap="round"/>
      <path class="ds-mid" d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="46.2" stroke-dasharray="1 36" stroke-linecap="round"/>
      <path class="ds-lb" stroke="url(#ds-g-colon)" d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="40"/>
      <path class="ds-mid" d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="28.0"/>
      <path class="ds-core" d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="15.2"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="6.8" transform="translate(-8.0,-8.0)"/>
      <path class="ds-seam" d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="70" stroke-dasharray="2.5 36" stroke-dashoffset="19.0"/>
      <path class="ds-taenia" d="M 318,1190 C 262,1178 236,1140 234,1084 C 230,978 228,850 238,772 C 244,712 280,682 336,678 C 404,674 446,712 488,766 C 552,844 640,858 712,798 C 770,748 802,678 862,654 C 900,638 918,662 918,712 C 918,806 920,1002 912,1092 C 906,1162 862,1210 796,1218 C 742,1224 700,1204 668,1228" stroke-width="3.6"/>
      <g class="ds-hit">
      <path d="M 306,1216 C 234,1204 198,1156 196,1086 C 192,978 190,848 200,762 C 208,690 254,648 328,644 C 412,640 462,684 508,744 C 566,820 640,832 706,776 C 764,726 796,650 862,622 C 918,598 950,638 950,706 C 958,802 960,1002 950,1096 C 946,1182 892,1242 808,1252 C 744,1260 692,1232 654,1262" stroke-width="54"/>
      </g>
    </g>
    <g class="ds-organ" data-organ="appendix" aria-label="Appendix">
      <path class="ds-edge" d="M 322,1222 C 342,1262 352,1290 348,1310" stroke-width="21.0"/>
      <path class="ds-lb" stroke="url(#ds-g-colon)" d="M 322,1222 C 342,1262 352,1290 348,1310" stroke-width="16"/>
      <path class="ds-mid" d="M 322,1222 C 342,1262 352,1290 348,1310" stroke-width="11.2"/>
      <path class="ds-core" d="M 322,1222 C 342,1262 352,1290 348,1310" stroke-width="6.1"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 322,1222 C 342,1262 352,1290 348,1310" stroke-width="2.7" transform="translate(-3.2,-3.2)"/>
      <g class="ds-hit">
      <path d="M 322,1222 C 342,1262 352,1290 348,1310" stroke-width="40"/>
      </g>
    </g>
    <g class="ds-organ" data-organ="rectum" aria-label="Rectum">
      <path class="ds-edge" d="M 654,1262 C 620,1288 602,1318 600,1356 C 598,1396 599,1424 600,1452" stroke-width="51.0"/>
      <path class="ds-lb" stroke="url(#ds-g-colon)" d="M 654,1262 C 620,1288 602,1318 600,1356 C 598,1396 599,1424 600,1452" stroke-width="46"/>
      <path class="ds-mid" d="M 654,1262 C 620,1288 602,1318 600,1356 C 598,1396 599,1424 600,1452" stroke-width="32.2"/>
      <path class="ds-core" d="M 654,1262 C 620,1288 602,1318 600,1356 C 598,1396 599,1424 600,1452" stroke-width="17.5"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 654,1262 C 620,1288 602,1318 600,1356 C 598,1396 599,1424 600,1452" stroke-width="7.8" transform="translate(-9.2,-9.2)"/>
      <g class="ds-hit">
      <path d="M 654,1262 C 620,1288 602,1318 600,1356 C 598,1396 599,1424 600,1452" stroke-width="60"/>
      </g>
    </g>
    <g class="ds-organ" data-organ="small-intestine" aria-label="Small intestine">
      <path class="ds-edge" d="M 700,760 C 766,778 800,840 770,890 C 744,928 692,934 664,910" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 700,760 C 766,778 800,840 770,890 C 744,928 692,934 664,910" stroke-width="42"/>
      <path class="ds-mid" d="M 700,760 C 766,778 800,840 770,890 C 744,928 692,934 664,910" stroke-width="29.4"/>
      <path class="ds-core" d="M 700,760 C 766,778 800,840 770,890 C 744,928 692,934 664,910" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 700,760 C 766,778 800,840 770,890 C 744,928 692,934 664,910" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 396,898 C 342,924 338,992 390,1014 C 432,1032 478,1010 486,974" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 396,898 C 342,924 338,992 390,1014 C 432,1032 478,1010 486,974" stroke-width="42"/>
      <path class="ds-mid" d="M 396,898 C 342,924 338,992 390,1014 C 432,1032 478,1010 486,974" stroke-width="29.4"/>
      <path class="ds-core" d="M 396,898 C 342,924 338,992 390,1014 C 432,1032 478,1010 486,974" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 396,898 C 342,924 338,992 390,1014 C 432,1032 478,1010 486,974" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 556,1162 C 620,1198 702,1176 730,1124 C 750,1086 732,1044 702,1030" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 556,1162 C 620,1198 702,1176 730,1124 C 750,1086 732,1044 702,1030" stroke-width="42"/>
      <path class="ds-mid" d="M 556,1162 C 620,1198 702,1176 730,1124 C 750,1086 732,1044 702,1030" stroke-width="29.4"/>
      <path class="ds-core" d="M 556,1162 C 620,1198 702,1176 730,1124 C 750,1086 732,1044 702,1030" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 556,1162 C 620,1198 702,1176 730,1124 C 750,1086 732,1044 702,1030" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 468,782 C 414,808 404,866 446,894" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 468,782 C 414,808 404,866 446,894" stroke-width="42"/>
      <path class="ds-mid" d="M 468,782 C 414,808 404,866 446,894" stroke-width="29.4"/>
      <path class="ds-core" d="M 468,782 C 414,808 404,866 446,894" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 468,782 C 414,808 404,866 446,894" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 592,910 C 644,896 692,920 702,960" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 592,910 C 644,896 692,920 702,960" stroke-width="42"/>
      <path class="ds-mid" d="M 592,910 C 644,896 692,920 702,960" stroke-width="29.4"/>
      <path class="ds-core" d="M 592,910 C 644,896 692,920 702,960" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 592,910 C 644,896 692,920 702,960" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 522,1094 C 470,1084 428,1110 426,1148" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 522,1094 C 470,1084 428,1110 426,1148" stroke-width="42"/>
      <path class="ds-mid" d="M 522,1094 C 470,1084 428,1110 426,1148" stroke-width="29.4"/>
      <path class="ds-core" d="M 522,1094 C 470,1084 428,1110 426,1148" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 522,1094 C 470,1084 428,1110 426,1148" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 612,616 C 668,634 706,624 736,640 C 772,660 776,706 748,724" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 612,616 C 668,634 706,624 736,640 C 772,660 776,706 748,724" stroke-width="42"/>
      <path class="ds-mid" d="M 612,616 C 668,634 706,624 736,640 C 772,660 776,706 748,724" stroke-width="29.4"/>
      <path class="ds-core" d="M 612,616 C 668,634 706,624 736,640 C 772,660 776,706 748,724" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 612,616 C 668,634 706,624 736,640 C 772,660 776,706 748,724" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 786,690 C 830,708 846,764 812,800 C 782,832 736,826 716,796" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 786,690 C 830,708 846,764 812,800 C 782,832 736,826 716,796" stroke-width="42"/>
      <path class="ds-mid" d="M 786,690 C 830,708 846,764 812,800 C 782,832 736,826 716,796" stroke-width="29.4"/>
      <path class="ds-core" d="M 786,690 C 830,708 846,764 812,800 C 782,832 736,826 716,796" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 786,690 C 830,708 846,764 812,800 C 782,832 736,826 716,796" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 358,986 C 318,1014 320,1074 362,1096 C 396,1114 436,1100 450,1072" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 358,986 C 318,1014 320,1074 362,1096 C 396,1114 436,1100 450,1072" stroke-width="42"/>
      <path class="ds-mid" d="M 358,986 C 318,1014 320,1074 362,1096 C 396,1114 436,1100 450,1072" stroke-width="29.4"/>
      <path class="ds-core" d="M 358,986 C 318,1014 320,1074 362,1096 C 396,1114 436,1100 450,1072" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 358,986 C 318,1014 320,1074 362,1096 C 396,1114 436,1100 450,1072" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 640,1128 C 594,1150 548,1136 522,1104" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 640,1128 C 594,1150 548,1136 522,1104" stroke-width="42"/>
      <path class="ds-mid" d="M 640,1128 C 594,1150 548,1136 522,1104" stroke-width="29.4"/>
      <path class="ds-core" d="M 640,1128 C 594,1150 548,1136 522,1104" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 640,1128 C 594,1150 548,1136 522,1104" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 754,996 C 800,1020 812,1084 774,1116 C 742,1144 698,1136 680,1108" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 754,996 C 800,1020 812,1084 774,1116 C 742,1144 698,1136 680,1108" stroke-width="42"/>
      <path class="ds-mid" d="M 754,996 C 800,1020 812,1084 774,1116 C 742,1144 698,1136 680,1108" stroke-width="29.4"/>
      <path class="ds-core" d="M 754,996 C 800,1020 812,1084 774,1116 C 742,1144 698,1136 680,1108" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 754,996 C 800,1020 812,1084 774,1116 C 742,1144 698,1136 680,1108" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 434,724 C 386,748 372,802 398,838" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 434,724 C 386,748 372,802 398,838" stroke-width="42"/>
      <path class="ds-mid" d="M 434,724 C 386,748 372,802 398,838" stroke-width="29.4"/>
      <path class="ds-core" d="M 434,724 C 386,748 372,802 398,838" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 434,724 C 386,748 372,802 398,838" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 386,1128 C 424,1166 486,1176 524,1152" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 386,1128 C 424,1166 486,1176 524,1152" stroke-width="42"/>
      <path class="ds-mid" d="M 386,1128 C 424,1166 486,1176 524,1152" stroke-width="29.4"/>
      <path class="ds-core" d="M 386,1128 C 424,1166 486,1176 524,1152" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 386,1128 C 424,1166 486,1176 524,1152" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 664,1044 C 620,1060 578,1046 560,1010" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 664,1044 C 620,1060 578,1046 560,1010" stroke-width="42"/>
      <path class="ds-mid" d="M 664,1044 C 620,1060 578,1046 560,1010" stroke-width="29.4"/>
      <path class="ds-core" d="M 664,1044 C 620,1060 578,1046 560,1010" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 664,1044 C 620,1060 578,1046 560,1010" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 480,932 C 528,908 586,928 604,972" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 480,932 C 528,908 586,928 604,972" stroke-width="42"/>
      <path class="ds-mid" d="M 480,932 C 528,908 586,928 604,972" stroke-width="29.4"/>
      <path class="ds-core" d="M 480,932 C 528,908 586,928 604,972" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 480,932 C 528,908 586,928 604,972" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 728,860 C 692,832 686,788 712,764" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 728,860 C 692,832 686,788 712,764" stroke-width="42"/>
      <path class="ds-mid" d="M 728,860 C 692,832 686,788 712,764" stroke-width="29.4"/>
      <path class="ds-core" d="M 728,860 C 692,832 686,788 712,764" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 728,860 C 692,832 686,788 712,764" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 340,1046 C 306,1074 306,1122 340,1146" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 340,1046 C 306,1074 306,1122 340,1146" stroke-width="42"/>
      <path class="ds-mid" d="M 340,1046 C 306,1074 306,1122 340,1146" stroke-width="29.4"/>
      <path class="ds-core" d="M 340,1046 C 306,1074 306,1122 340,1146" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 340,1046 C 306,1074 306,1122 340,1146" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 596,1204 C 654,1228 716,1212 742,1170" stroke-width="47.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 596,1204 C 654,1228 716,1212 742,1170" stroke-width="42"/>
      <path class="ds-mid" d="M 596,1204 C 654,1228 716,1212 742,1170" stroke-width="29.4"/>
      <path class="ds-core" d="M 596,1204 C 654,1228 716,1212 742,1170" stroke-width="16.0"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 596,1204 C 654,1228 716,1212 742,1170" stroke-width="7.1" transform="translate(-8.4,-8.4)"/>
      <path class="ds-edge" d="M 651,700 C 578,724 500,690 452,738 C 400,790 424,856 494,856 C 558,856 602,818 656,838 C 722,862 762,908 746,962 C 730,1016 660,1024 616,988 C 566,948 588,884 532,868 C 472,851 420,902 442,958 C 462,1008 524,1018 548,1064 C 574,1112 532,1156 482,1146 C 428,1135 418,1076 470,1046 C 522,1016 596,1042 640,1082 C 676,1114 668,1178 616,1196 C 560,1214 502,1180 470,1140" stroke-width="51.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 651,700 C 578,724 500,690 452,738 C 400,790 424,856 494,856 C 558,856 602,818 656,838 C 722,862 762,908 746,962 C 730,1016 660,1024 616,988 C 566,948 588,884 532,868 C 472,851 420,902 442,958 C 462,1008 524,1018 548,1064 C 574,1112 532,1156 482,1146 C 428,1135 418,1076 470,1046 C 522,1016 596,1042 640,1082 C 676,1114 668,1178 616,1196 C 560,1214 502,1180 470,1140" stroke-width="46"/>
      <path class="ds-mid" d="M 651,700 C 578,724 500,690 452,738 C 400,790 424,856 494,856 C 558,856 602,818 656,838 C 722,862 762,908 746,962 C 730,1016 660,1024 616,988 C 566,948 588,884 532,868 C 472,851 420,902 442,958 C 462,1008 524,1018 548,1064 C 574,1112 532,1156 482,1146 C 428,1135 418,1076 470,1046 C 522,1016 596,1042 640,1082 C 676,1114 668,1178 616,1196 C 560,1214 502,1180 470,1140" stroke-width="32.2"/>
      <path class="ds-core" d="M 651,700 C 578,724 500,690 452,738 C 400,790 424,856 494,856 C 558,856 602,818 656,838 C 722,862 762,908 746,962 C 730,1016 660,1024 616,988 C 566,948 588,884 532,868 C 472,851 420,902 442,958 C 462,1008 524,1018 548,1064 C 574,1112 532,1156 482,1146 C 428,1135 418,1076 470,1046 C 522,1016 596,1042 640,1082 C 676,1114 668,1178 616,1196 C 560,1214 502,1180 470,1140" stroke-width="17.5"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 651,700 C 578,724 500,690 452,738 C 400,790 424,856 494,856 C 558,856 602,818 656,838 C 722,862 762,908 746,962 C 730,1016 660,1024 616,988 C 566,948 588,884 532,868 C 472,851 420,902 442,958 C 462,1008 524,1018 548,1064 C 574,1112 532,1156 482,1146 C 428,1135 418,1076 470,1046 C 522,1016 596,1042 640,1082 C 676,1114 668,1178 616,1196 C 560,1214 502,1180 470,1140" stroke-width="7.8" transform="translate(-9.2,-9.2)"/>
      <g class="ds-hit">
      <path d="M 700,760 C 766,778 800,840 770,890 C 744,928 692,934 664,910" stroke-width="56"/>
      <path d="M 396,898 C 342,924 338,992 390,1014 C 432,1032 478,1010 486,974" stroke-width="56"/>
      <path d="M 556,1162 C 620,1198 702,1176 730,1124 C 750,1086 732,1044 702,1030" stroke-width="56"/>
      <path d="M 468,782 C 414,808 404,866 446,894" stroke-width="56"/>
      <path d="M 592,910 C 644,896 692,920 702,960" stroke-width="56"/>
      <path d="M 522,1094 C 470,1084 428,1110 426,1148" stroke-width="56"/>
      <path d="M 612,616 C 668,634 706,624 736,640 C 772,660 776,706 748,724" stroke-width="56"/>
      <path d="M 786,690 C 830,708 846,764 812,800 C 782,832 736,826 716,796" stroke-width="56"/>
      <path d="M 358,986 C 318,1014 320,1074 362,1096 C 396,1114 436,1100 450,1072" stroke-width="56"/>
      <path d="M 640,1128 C 594,1150 548,1136 522,1104" stroke-width="56"/>
      <path d="M 754,996 C 800,1020 812,1084 774,1116 C 742,1144 698,1136 680,1108" stroke-width="56"/>
      <path d="M 434,724 C 386,748 372,802 398,838" stroke-width="56"/>
      <path d="M 386,1128 C 424,1166 486,1176 524,1152" stroke-width="56"/>
      <path d="M 664,1044 C 620,1060 578,1046 560,1010" stroke-width="56"/>
      <path d="M 480,932 C 528,908 586,928 604,972" stroke-width="56"/>
      <path d="M 728,860 C 692,832 686,788 712,764" stroke-width="56"/>
      <path d="M 340,1046 C 306,1074 306,1122 340,1146" stroke-width="56"/>
      <path d="M 596,1204 C 654,1228 716,1212 742,1170" stroke-width="56"/>
      <path d="M 651,700 C 578,724 500,690 452,738 C 400,790 424,856 494,856 C 558,856 602,818 656,838 C 722,862 762,908 746,962 C 730,1016 660,1024 616,988 C 566,948 588,884 532,868 C 472,851 420,902 442,958 C 462,1008 524,1018 548,1064 C 574,1112 532,1156 482,1146 C 428,1135 418,1076 470,1046 C 522,1016 596,1042 640,1082 C 676,1114 668,1178 616,1196 C 560,1214 502,1180 470,1140" stroke-width="60"/>
      </g>
    </g>
    <g class="ds-organ" data-organ="duodenum" aria-label="Duodenum">
      <path class="ds-edge" d="M 504,492 C 456,480 420,506 410,554 C 397,614 424,660 476,678 C 532,698 600,688 648,704" stroke-width="49.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 504,492 C 456,480 420,506 410,554 C 397,614 424,660 476,678 C 532,698 600,688 648,704" stroke-width="44"/>
      <path class="ds-mid" d="M 504,492 C 456,480 420,506 410,554 C 397,614 424,660 476,678 C 532,698 600,688 648,704" stroke-width="30.8"/>
      <path class="ds-core" d="M 504,492 C 456,480 420,506 410,554 C 397,614 424,660 476,678 C 532,698 600,688 648,704" stroke-width="16.7"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 504,492 C 456,480 420,506 410,554 C 397,614 424,660 476,678 C 532,698 600,688 648,704" stroke-width="7.5" transform="translate(-8.8,-8.8)"/>
      <g class="ds-hit">
      <path d="M 504,492 C 456,480 420,506 410,554 C 397,614 424,660 476,678 C 532,698 600,688 648,704" stroke-width="58"/>
      </g>
    </g>
    <g class="ds-organ" data-organ="oesophagus" aria-label="Oesophagus">
      <path class="ds-edge" d="M 611,-10 C 611,90 604,190 606,250 C 608,302 626,330 664,346" stroke-width="25.0"/>
      <path class="ds-sb" stroke="url(#ds-g-tube)" d="M 611,-10 C 611,90 604,190 606,250 C 608,302 626,330 664,346" stroke-width="20"/>
      <path class="ds-mid" d="M 611,-10 C 611,90 604,190 606,250 C 608,302 626,330 664,346" stroke-width="14.0"/>
      <path class="ds-core" d="M 611,-10 C 611,90 604,190 606,250 C 608,302 626,330 664,346" stroke-width="7.6"/>
      <path class="ds-sheen" filter="url(#ds-f-soft)" d="M 611,-10 C 611,90 604,190 606,250 C 608,302 626,330 664,346" stroke-width="3.4" transform="translate(-4.0,-4.0)"/>
      <g class="ds-hit">
      <path d="M 611,-10 C 611,90 604,190 606,250 C 608,302 626,330 664,346" stroke-width="40"/>
      </g>
    </g>
    <g class="ds-organ" data-organ="stomach" aria-label="Stomach">
      <path d="M 656,336 C 690,306 744,286 800,290 C 872,296 924,348 928,424 C 932,498 898,562 838,592 C 790,616 736,614 692,592 C 650,572 606,550 568,538 C 542,530 516,520 500,508 C 494,494 498,482 510,474 C 556,488 606,506 644,522 C 676,534 704,526 718,500 C 730,472 726,428 706,390 C 692,364 674,346 656,336 Z" fill="none" stroke="var(--ds-glow,#8FE0FA)"
            stroke-opacity=".45" stroke-width="18" stroke-linejoin="round"
            filter="url(#ds-f-glow)"/>
      <path d="M 656,336 C 690,306 744,286 800,290 C 872,296 924,348 928,424 C 932,498 898,562 838,592 C 790,616 736,614 692,592 C 650,572 606,550 568,538 C 542,530 516,520 500,508 C 494,494 498,482 510,474 C 556,488 606,506 644,522 C 676,534 704,526 718,500 C 730,472 726,428 706,390 C 692,364 674,346 656,336 Z" fill="url(#ds-g-stomach)" stroke="var(--ds-edge,#E8FAFF)"
            stroke-opacity=".9" stroke-width="3.5" stroke-linejoin="round"/>
      <path d="M 690,336 C 740,308 800,296 856,320" fill="none" stroke="#FFFFFF"
            stroke-opacity=".55" stroke-width="16" stroke-linecap="round"
            filter="url(#ds-f-soft)"/>
      <path d="M 896,388 C 916,424 918,468 906,506" fill="none" stroke="#FFFFFF"
            stroke-opacity=".85" stroke-width="9" stroke-linecap="round"
            filter="url(#ds-f-soft)"/>
      <path d="M 700,470 C 690,506 660,522 626,512" fill="none" stroke="#EAFBFF"
            stroke-opacity=".55" stroke-width="4" stroke-linecap="round"/>
      <path d="M 556,514 C 620,536 690,578 760,590" fill="none" stroke="var(--ds-seam,#6F8FDE)"
            stroke-opacity=".35" stroke-width="4" stroke-linecap="round"/>
      <g fill="none" stroke="var(--ds-seam,#79A0E8)" stroke-opacity=".30" stroke-width="3.2"
         stroke-linecap="round">
        <path d="M 706,330 C 692,372 686,420 694,462"/>
        <path d="M 776,294 C 768,346 770,400 786,448"/>
        <path d="M 848,300 C 852,352 858,404 872,450"/>
      </g>
    </g>
  </g>`;

let uid = 0;

/** Scope every gradient/filter id to one instance.
 *  The defs live INSIDE each element so that per-instance CSS custom
 *  properties (--ds-rim-1 and friends) actually reach the gradient stops —
 *  a shared sprite in <body> cannot inherit them. */
function scope(markup, n) {
  return markup.replace(/ds-(g|f)-([a-z-]+)/g, `ds-$1-$2-${n}`);
}

const nameOf = (organ, lang) => (lang === "ar" ? organ.ar : organ.en);

export class DigestiveSystem extends HTMLElement {
  static observedAttributes = ["selected", "lang", "interactive", "caption"];

  #svg = null;
  #ring = null;
  #caption = null;
  #hovered = null;

  connectedCallback() {
    if (this.#svg) return;
    this.#render();
  }

  attributeChangedCallback() {
    if (!this.#svg) return;
    this.#syncLabels();
    this.#paint();
  }

  /** Currently selected organ id, or null. */
  get selected() { return this.getAttribute("selected"); }
  set selected(id) {
    if (id) this.setAttribute("selected", id);
    else this.removeAttribute("selected");
  }

  get organs() { return ORGANS.slice(); }

  /** Select an organ programmatically; fires organ-select. */
  select(id) {
    const organ = ORGANS.find((o) => o.id === id);
    if (!organ) return false;
    this.selected = id;
    this.#emit("organ-select", { id, name: nameOf(organ, this.lang) });
    return true;
  }

  /** Clear selection and hover state. */
  clear() {
    this.selected = null;
    this.#hovered = null;
    this.#paint();
  }

  get lang() { return this.getAttribute("lang") === "ar" ? "ar" : "en"; }

  // ------------------------------------------------------------- internals
  #render() {
    const ns = "http://www.w3.org/2000/svg";
    const svg = document.createElementNS(ns, "svg");
    svg.setAttribute("class", "ds-svg");
    svg.setAttribute("viewBox", `0 0 ${VIEWBOX.width} ${VIEWBOX.height}`);
    svg.setAttribute("role", "img");
    svg.setAttribute("aria-label", this.getAttribute("aria-label") ||
      "Human digestive system");
    const n = ++uid;
    svg.innerHTML = `<defs>${scope(DEFS, n)}</defs>${scope(ART, n)}`;

    const ring = document.createElementNS(ns, "rect");
    ring.setAttribute("class", "ds-focus-ring");
    ring.hidden = true;
    svg.append(ring);

    this.#svg = svg;
    this.#ring = ring;
    this.append(svg);

    const labels = document.createElement("div");
    labels.className = "ds-labels";
    for (const organ of ORGANS) {
      const el = document.createElement("span");
      el.className = "ds-label";
      el.dataset.organ = organ.id;
      el.style.left = `${organ.x}%`;   // physical, not logical: the anchors
      el.style.top = `${organ.y}%`;     // are viewBox coordinates, never RTL

      labels.append(el);
    }
    this.append(labels);

    const caption = document.createElement("p");
    caption.className = "ds-caption";
    caption.setAttribute("aria-live", "polite");
    this.#caption = caption;
    this.append(caption);

    this.#syncLabels();
    this.#wire();
    this.#paint();
  }

  #groups(selector = ".ds-organ, .ds-organ-glow") {
    return this.#svg.querySelectorAll(selector);
  }

  #wire() {
    for (const g of this.#svg.querySelectorAll(".ds-organ")) {
      const id = g.dataset.organ;
      g.addEventListener("pointerenter", () => this.#hover(id));
      g.addEventListener("pointerleave", () => this.#hover(null));
      g.addEventListener("click", () => this.#activate(id));
      g.addEventListener("keydown", (e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          this.#activate(id);
        } else if (e.key === "Escape") {
          this.clear();
        }
      });
      // :focus-visible so the ring answers the keyboard, not every mouse click
      g.addEventListener("focus", () => {
        this.#hover(id);
        this.#ringTo(g.matches(":focus-visible") ? g : null);
      });
      g.addEventListener("blur", () => { this.#hover(null); this.#ringTo(null); });
    }
  }

  #interactive() { return this.hasAttribute("interactive"); }

  #hover(id) {
    if (!this.#interactive()) return;
    this.#hovered = id;
    this.#emit("organ-hover", id
      ? { id, name: nameOf(ORGANS.find((o) => o.id === id), this.lang) }
      : { id: null, name: null });
    this.#paint();
  }

  #activate(id) {
    if (!this.#interactive()) return;
    if (this.selected === id) this.clear();
    else this.select(id);
  }

  #ringTo(g) {
    if (!g || !this.#interactive()) { this.#ring.hidden = true; return; }
    const box = g.getBBox();
    const pad = 10;
    this.#ring.setAttribute("x", box.x - pad);
    this.#ring.setAttribute("y", box.y - pad);
    this.#ring.setAttribute("width", box.width + pad * 2);
    this.#ring.setAttribute("height", box.height + pad * 2);
    this.#ring.hidden = false;
  }

  #syncLabels() {
    const lang = this.lang;
    this.dataset.lang = lang;
    for (const el of this.querySelectorAll(".ds-label")) {
      const organ = ORGANS.find((o) => o.id === el.dataset.organ);
      el.textContent = nameOf(organ, lang);
    }
    for (const g of this.#svg.querySelectorAll(".ds-organ")) {
      const organ = ORGANS.find((o) => o.id === g.dataset.organ);
      g.setAttribute("aria-label", nameOf(organ, lang));
    }
  }

  /** Apply active/dimmed classes; the single place that touches the DOM state. */
  #paint() {
    const on = this.#interactive();
    const active = this.#hovered || this.selected;

    for (const g of this.#svg.querySelectorAll(".ds-organ")) {
      if (on) {
        g.setAttribute("role", "button");
        g.setAttribute("tabindex", "0");
      } else {
        g.removeAttribute("role");
        g.removeAttribute("tabindex");
      }
      g.setAttribute("aria-pressed", String(this.selected === g.dataset.organ));
    }

    for (const g of this.#groups()) {
      const isActive = Boolean(active) && g.dataset.organ === active;
      g.classList.toggle("is-active", isActive && g.classList.contains("ds-organ"));
      g.classList.toggle("is-dimmed", Boolean(active) && !isActive);
    }
    for (const el of this.querySelectorAll(".ds-label")) {
      el.classList.toggle("is-dimmed",
        Boolean(active) && el.dataset.organ !== active);
    }

    if (this.#caption) {
      const organ = ORGANS.find((o) => o.id === active);
      this.#caption.textContent = organ
        ? nameOf(organ, this.lang)
        : (this.lang === "ar" ? "الجهاز الهضمي" : "Digestive system");
    }
  }

  #emit(type, detail) {
    this.dispatchEvent(new CustomEvent(type, {
      detail, bubbles: true, composed: true,
    }));
  }
}

if (!customElements.get("digestive-system")) {
  customElements.define("digestive-system", DigestiveSystem);
}

export default DigestiveSystem;
